FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/db/sqlalchemy/api.py
TARGET CLASS: None
TARGET FUNCTION DEF: _instance_update+2815;8
FAULT POINT: _instance_metadata_update_in_place(context, instance_ref, 'system_metadata', models.InstanceSystemMetadata, system_metadata)
