FAULT TYPE: OPENSTACK_THROW_EXCEPTION-VOLUME
TARGET COMPONENT: /cinder/objects/volume.py
TARGET CLASS: Volume
TARGET FUNCTION DEF: save+389;16
FAULT POINT: db.volume_update(self._context, self.id, updates)
