FAULT TYPE: OPENSTACK_THROW_EXCEPTION-NETWORK
TARGET COMPONENT: /nova/network/neutronv2/api.py
TARGET CLASS: API
TARGET FUNCTION DEF: _validate_requested_network_ids+747;8
FAULT POINT: self._check_external_network_attach(context, nets)
