FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/api.py
TARGET CLASS: API
TARGET FUNCTION DEF: create_db_entry_for_new_instance+1582;8
FAULT POINT: self._populate_instance_for_create(context, instance, image, index, security_group, instance_type, num_instances, shutdown_terminate)
